### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by njh** [acook/remedy#1]
Hello,

I was looking for a ruby gem to allow me to detect key presses and found Remedy.

However I tried the example:

``` ruby
require 'remedy'
include Remedy

user_input = Interaction.new
user_input.loop do |key|
  puts key
end
```

And had problems with _$log_:

```
ruby remedy-test.rb 
/Users/humfrn01/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/remedy-0.0.4/lib/remedy/keyboard.rb:27:in `parse': undefined method `debug' for nil:NilClass (NoMethodError)
        from /Users/humfrn01/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/remedy-0.0.4/lib/remedy/keyboard.rb:9:in `get'
        from /Users/humfrn01/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/remedy-0.0.4/lib/remedy/interaction.rb:53:in `block in loop'
        from /Users/humfrn01/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/remedy-0.0.4/lib/remedy/interaction.rb:49:in `loop'
        from /Users/humfrn01/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/remedy-0.0.4/lib/remedy/interaction.rb:49:in `loop'
        from remedy-test.rb:5:in `<main>'
```

Is there something I am missing?

nick.

**Comment by acook** [comment]
Ah, sorry about that. I'll push a fix to Rubygems ASAP, thanks for the bug report!

Background for the interested: Remedy was extracted from a larger project which assumed a `$log` (in this case [Logsaber](http://www.github.com/acook/logsaber)).

**Comment by acook** [comment]
It's live: https://rubygems.org/gems/remedy
Thanks again!

**Comment by njh** [comment]
Confirmed working, thank you!
